/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'ui-monospace', 'monospace'],
      },
      colors: {
        /* ── Theme-aware dynamic colors mapping to App.css variables ── */
        bg:           'var(--bg)',
        surface:      'var(--surface)',
        'surface-2':  'var(--surface-2)',
        'surface-3':  'var(--surface-3)',
        border:       'var(--border)',
        'border-2':   'var(--border-2)',
        'border-3':   'var(--border-3)',
        text:         'var(--text)',
        'text-strong':'var(--text-strong)',
        'text-2':     'var(--text-2)',
        'text-3':     'var(--text-3)',
        white:        'var(--white)',
        green:        'var(--green)',
        'green-dim':  'var(--green-dim)',
        red:          'var(--red)',
        'red-dim':    'var(--red-dim)',
        amber:        'var(--amber)',
        'amber-dim':  'var(--amber-dim)',
        blue:         'var(--blue)',
        'blue-dim':   'var(--blue-dim)',
        teal:         'var(--teal)',
        accent:       'var(--accent)',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '0px',
      },
      boxShadow: {
        DEFAULT: 'none',
        sm: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        inner: 'none',
        none: 'none',
      },
      fontWeight: {
        700: '700',
        800: '800',
        900: '900',
      },
    },
  },
  plugins: [],
}
